# Generated by Django 2.0.4 on 2018-04-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start_selling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('inventory', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='items')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start_selling.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='solditem',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start_selling.Transaction'),
        ),
    ]
