# Generated by Django 2.0.4 on 2018-04-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_selling', '0003_auto_20180423_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solditem',
            old_name='transaction',
            new_name='transactio',
        ),
    ]
