# Generated by Django 2.0.4 on 2018-04-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_selling', '0004_auto_20180423_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solditem',
            old_name='transactio',
            new_name='transaction',
        ),
    ]
