# Generated by Django 2.0.4 on 2018-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_selling', '0006_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
